#!/bin/sh
# Dyad/Vercel ortamında pnpm çağrılarını npm'e yönlendirir
case "$1" in
  install|i)
    shift
    exec npm install "$@"
    ;;
  run)
    shift
    exec npm run "$@"
    ;;
  *)
    exec npm "$@"
    ;;
esac